<?php
echo '<header id="index_header"><!--This is the top section for every page, which has links to either portal and other pages-->
    <h1 id="companyName">Bullseye Databases</h1>
        <nav id="navCenter">
            <a class="header-main-nav" href="Recorder.php">Recorder Portal</a>
	    <a class="header-main-nav" href="ArcherScoreSubmission.php">Score Submission</a>
            <a class="header-main-nav" href="ArcherScores.php">Scores</a>
            <a class="header-main-nav" href="ArcherRounds.php">Rounds</a>
            <a class="header-main-nav" href="Results.php">Results</a>
        </nav>
        </nav>
<hr>
</header>';
?>